# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lab_management_system_fastapi.models.auth_state_anonymous import AuthStateAnonymous
from lab_management_system_fastapi.models.auth_state_authenticated import AuthStateAuthenticated
from lab_management_system_fastapi.models.auth_state_awaiting_tenant import AuthStateAwaitingTenant
from lab_management_system_fastapi.models.auth_state_idle import AuthStateIdle
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

AUTHSTATE_ONE_OF_SCHEMAS = ["AuthStateAnonymous", "AuthStateAuthenticated", "AuthStateAwaitingTenant", "AuthStateIdle"]

class AuthState(BaseModel):
    """
    auth 状态机 4 态。Vue: pinia store / React: Context;两侧实现可同构
    """
    # data type: AuthStateIdle
    oneof_schema_1_validator: Optional[AuthStateIdle] = None
    # data type: AuthStateAnonymous
    oneof_schema_2_validator: Optional[AuthStateAnonymous] = None
    # data type: AuthStateAwaitingTenant
    oneof_schema_3_validator: Optional[AuthStateAwaitingTenant] = None
    # data type: AuthStateAuthenticated
    oneof_schema_4_validator: Optional[AuthStateAuthenticated] = None
    actual_instance: Optional[Union[AuthStateAnonymous, AuthStateAuthenticated, AuthStateAwaitingTenant, AuthStateIdle]] = None
    one_of_schemas: List[str] = Literal["AuthStateAnonymous", "AuthStateAuthenticated", "AuthStateAwaitingTenant", "AuthStateIdle"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = AuthState.model_construct()
        error_messages = []
        match = 0
        # validate data type: AuthStateIdle
        if not isinstance(v, AuthStateIdle):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStateIdle`")
        else:
            match += 1
        # validate data type: AuthStateAnonymous
        if not isinstance(v, AuthStateAnonymous):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStateAnonymous`")
        else:
            match += 1
        # validate data type: AuthStateAwaitingTenant
        if not isinstance(v, AuthStateAwaitingTenant):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStateAwaitingTenant`")
        else:
            match += 1
        # validate data type: AuthStateAuthenticated
        if not isinstance(v, AuthStateAuthenticated):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthStateAuthenticated`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in AuthState with oneOf schemas: AuthStateAnonymous, AuthStateAuthenticated, AuthStateAwaitingTenant, AuthStateIdle. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in AuthState with oneOf schemas: AuthStateAnonymous, AuthStateAuthenticated, AuthStateAwaitingTenant, AuthStateIdle. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into AuthStateIdle
        try:
            instance.actual_instance = AuthStateIdle.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AuthStateAnonymous
        try:
            instance.actual_instance = AuthStateAnonymous.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AuthStateAwaitingTenant
        try:
            instance.actual_instance = AuthStateAwaitingTenant.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into AuthStateAuthenticated
        try:
            instance.actual_instance = AuthStateAuthenticated.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into AuthState with oneOf schemas: AuthStateAnonymous, AuthStateAuthenticated, AuthStateAwaitingTenant, AuthStateIdle. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into AuthState with oneOf schemas: AuthStateAnonymous, AuthStateAuthenticated, AuthStateAwaitingTenant, AuthStateIdle. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


