# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from lab_management_system_fastapi.models.current_user import CurrentUser
from lab_management_system_fastapi.models.my_tenant import MyTenant
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AuthStateAuthenticatedValue(BaseModel):
    """
    AuthStateAuthenticatedValue
    """ # noqa: E501
    kind: StrictStr
    user: CurrentUser
    tenant: MyTenant
    permissions: List[StrictStr]
    token_expires_at: StrictInt = Field(description="unix ms", alias="tokenExpiresAt")
    __properties: ClassVar[List[str]] = ["kind", "user", "tenant", "permissions", "tokenExpiresAt"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('authenticated',):
            raise ValueError("must be one of enum values ('authenticated')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuthStateAuthenticatedValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tenant
        if self.tenant:
            _dict['tenant'] = self.tenant.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AuthStateAuthenticatedValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "user": CurrentUser.from_dict(obj.get("user")) if obj.get("user") is not None else None,
            "tenant": MyTenant.from_dict(obj.get("tenant")) if obj.get("tenant") is not None else None,
            "permissions": obj.get("permissions"),
            "tokenExpiresAt": obj.get("tokenExpiresAt")
        })
        return _obj


