# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class BackendId(str, Enum):
    """
    已废弃 (ADR-0014);3 个槽位,id 锁定避免拼写漂移。msw 成员 2026-09-17 随 msw 仓剔除删除
    """

    """
    allowed enum values
    """
    NEXTJS = 'nextjs'
    SPRINGBOOT = 'springboot'
    ASPNETCORE = 'aspnetcore'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BackendId from a JSON string"""
        return cls(json.loads(json_str))


