# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lab_management_system_fastapi.models.auth_header_kind import AuthHeaderKind
from lab_management_system_fastapi.models.backend_features import BackendFeatures
from lab_management_system_fastapi.models.backend_id import BackendId
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BackendConfig(BaseModel):
    """
    已废弃 (ADR-0014):用 VITE_API_BASE_URL / NEXT_PUBLIC_API_BASE_URL 替代;4-backend 运行时切换配置
    """ # noqa: E501
    id: BackendId = Field(description="槽位标识,必须是 BackendId 之一")
    label: StrictStr = Field(description="显示名(MSW Mock / Next.js API / Spring Boot / ASP.NET Core)")
    base_url: StrictStr = Field(description="baseUrl 的展示值,例如 'http://localhost:5201/api'", alias="baseUrl")
    auth_header: AuthHeaderKind = Field(description="token 头:Bearer 走 Authorization,部分老后端用 X-Auth-Token", alias="authHeader")
    sso_callback_path: Optional[StrictStr] = Field(default=None, description="SSO 回调路径(仅启用 SSO 的后端填写)", alias="ssoCallbackPath")
    features: BackendFeatures = Field(description="能力矩阵")
    __properties: ClassVar[List[str]] = ["id", "label", "baseUrl", "authHeader", "ssoCallbackPath", "features"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BackendConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of features
        if self.features:
            _dict['features'] = self.features.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BackendConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "label": obj.get("label"),
            "baseUrl": obj.get("baseUrl"),
            "authHeader": obj.get("authHeader"),
            "ssoCallbackPath": obj.get("ssoCallbackPath"),
            "features": BackendFeatures.from_dict(obj.get("features")) if obj.get("features") is not None else None
        })
        return _obj


