# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lab_management_system_fastapi.models.calculation_algorithm_type import CalculationAlgorithmType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CalculationMethod(BaseModel):
    """
    CalculationMethod
    """ # noqa: E501
    inspection_object_code: StrictStr = Field(alias="inspectionObjectCode")
    inspection_parameter_code: StrictStr = Field(alias="inspectionParameterCode")
    testing_standard_code: Optional[StrictStr] = Field(default=None, alias="testingStandardCode")
    report_name_code: Optional[StrictStr] = Field(default=None, alias="reportNameCode")
    algorithm_type: CalculationAlgorithmType = Field(alias="algorithmType")
    specimen_count: StrictInt = Field(alias="specimenCount")
    formula: Optional[StrictStr] = None
    conditions: Optional[StrictStr] = None
    rounding_rule: Optional[StrictStr] = Field(default=None, alias="roundingRule")
    remark: Optional[StrictStr] = None
    sort_order: StrictInt = Field(alias="sortOrder")
    created_at: StrictStr = Field(alias="createdAt")
    updated_at: StrictStr = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["inspectionObjectCode", "inspectionParameterCode", "testingStandardCode", "reportNameCode", "algorithmType", "specimenCount", "formula", "conditions", "roundingRule", "remark", "sortOrder", "createdAt", "updatedAt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CalculationMethod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CalculationMethod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "inspectionObjectCode": obj.get("inspectionObjectCode"),
            "inspectionParameterCode": obj.get("inspectionParameterCode"),
            "testingStandardCode": obj.get("testingStandardCode"),
            "reportNameCode": obj.get("reportNameCode"),
            "algorithmType": obj.get("algorithmType"),
            "specimenCount": obj.get("specimenCount"),
            "formula": obj.get("formula"),
            "conditions": obj.get("conditions"),
            "roundingRule": obj.get("roundingRule"),
            "remark": obj.get("remark"),
            "sortOrder": obj.get("sortOrder"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


