# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lab_management_system_fastapi.models.contract_status import ContractStatus
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreateContractRequest(BaseModel):
    """
    CreateContractRequest
    """ # noqa: E501
    contract_code: StrictStr = Field(alias="contractCode")
    client_unit: StrictStr = Field(alias="clientUnit")
    project_name: StrictStr = Field(alias="projectName")
    project_location: Optional[StrictStr] = Field(default=None, alias="projectLocation")
    construction_unit: StrictStr = Field(alias="constructionUnit")
    inspection_specialty_code: Optional[StrictStr] = Field(default=None, alias="inspectionSpecialtyCode")
    building_unit: Optional[StrictStr] = Field(default=None, alias="buildingUnit")
    supervisor_unit: Optional[StrictStr] = Field(default=None, alias="supervisorUnit")
    inspection_person: Optional[StrictStr] = Field(default=None, alias="inspectionPerson")
    inspection_phone: Optional[StrictStr] = Field(default=None, alias="inspectionPhone")
    witness_unit: StrictStr = Field(alias="witnessUnit")
    witness: StrictStr
    witness_phone: Optional[StrictStr] = Field(default=None, alias="witnessPhone")
    contact_person: Optional[StrictStr] = Field(default=None, alias="contactPerson")
    contact_phone: Optional[StrictStr] = Field(default=None, alias="contactPhone")
    entrusted_date: Optional[StrictStr] = Field(default=None, alias="entrustedDate")
    status: Optional[ContractStatus] = None
    __properties: ClassVar[List[str]] = ["contractCode", "clientUnit", "projectName", "projectLocation", "constructionUnit", "inspectionSpecialtyCode", "buildingUnit", "supervisorUnit", "inspectionPerson", "inspectionPhone", "witnessUnit", "witness", "witnessPhone", "contactPerson", "contactPhone", "entrustedDate", "status"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateContractRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateContractRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contractCode": obj.get("contractCode"),
            "clientUnit": obj.get("clientUnit"),
            "projectName": obj.get("projectName"),
            "projectLocation": obj.get("projectLocation"),
            "constructionUnit": obj.get("constructionUnit"),
            "inspectionSpecialtyCode": obj.get("inspectionSpecialtyCode"),
            "buildingUnit": obj.get("buildingUnit"),
            "supervisorUnit": obj.get("supervisorUnit"),
            "inspectionPerson": obj.get("inspectionPerson"),
            "inspectionPhone": obj.get("inspectionPhone"),
            "witnessUnit": obj.get("witnessUnit"),
            "witness": obj.get("witness"),
            "witnessPhone": obj.get("witnessPhone"),
            "contactPerson": obj.get("contactPerson"),
            "contactPhone": obj.get("contactPhone"),
            "entrustedDate": obj.get("entrustedDate"),
            "status": obj.get("status")
        })
        return _obj


