# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from lab_management_system_fastapi.models.material_qualified_rate import MaterialQualifiedRate
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DashboardStatsQualifiedRateByMaterial(BaseModel):
    """
    DashboardStatsQualifiedRateByMaterial
    """ # noqa: E501
    concrete: MaterialQualifiedRate
    rebar: MaterialQualifiedRate
    sand: MaterialQualifiedRate
    __properties: ClassVar[List[str]] = ["concrete", "rebar", "sand"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DashboardStatsQualifiedRateByMaterial from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of concrete
        if self.concrete:
            _dict['concrete'] = self.concrete.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rebar
        if self.rebar:
            _dict['rebar'] = self.rebar.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sand
        if self.sand:
            _dict['sand'] = self.sand.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DashboardStatsQualifiedRateByMaterial from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "concrete": MaterialQualifiedRate.from_dict(obj.get("concrete")) if obj.get("concrete") is not None else None,
            "rebar": MaterialQualifiedRate.from_dict(obj.get("rebar")) if obj.get("rebar") is not None else None,
            "sand": MaterialQualifiedRate.from_dict(obj.get("sand")) if obj.get("sand") is not None else None
        })
        return _obj


