# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from lab_management_system_fastapi.models.dashboard_stats_funnel_by_stage import DashboardStatsFunnelByStage
from lab_management_system_fastapi.models.dashboard_stats_qualified_rate_by_material import DashboardStatsQualifiedRateByMaterial
from lab_management_system_fastapi.models.dashboard_stats_report_count_by_status import DashboardStatsReportCountByStatus
from lab_management_system_fastapi.models.dashboard_stats_report_output_by_status import DashboardStatsReportOutputByStatus
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DashboardStats(BaseModel):
    """
    DashboardStats
    """ # noqa: E501
    contract_count: StrictInt = Field(alias="contractCount")
    receipt_count: StrictInt = Field(alias="receiptCount")
    sample_count: StrictInt = Field(alias="sampleCount")
    report_count_by_status: DashboardStatsReportCountByStatus = Field(alias="reportCountByStatus")
    pending_task_count: StrictInt = Field(alias="pendingTaskCount")
    today_test_count: StrictInt = Field(alias="todayTestCount")
    qualified_rate_by_material: DashboardStatsQualifiedRateByMaterial = Field(alias="qualifiedRateByMaterial")
    report_output_by_status: DashboardStatsReportOutputByStatus = Field(alias="reportOutputByStatus")
    funnel_by_stage: DashboardStatsFunnelByStage = Field(alias="funnelByStage")
    __properties: ClassVar[List[str]] = ["contractCount", "receiptCount", "sampleCount", "reportCountByStatus", "pendingTaskCount", "todayTestCount", "qualifiedRateByMaterial", "reportOutputByStatus", "funnelByStage"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DashboardStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of report_count_by_status
        if self.report_count_by_status:
            _dict['reportCountByStatus'] = self.report_count_by_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of qualified_rate_by_material
        if self.qualified_rate_by_material:
            _dict['qualifiedRateByMaterial'] = self.qualified_rate_by_material.to_dict()
        # override the default output from pydantic by calling `to_dict()` of report_output_by_status
        if self.report_output_by_status:
            _dict['reportOutputByStatus'] = self.report_output_by_status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of funnel_by_stage
        if self.funnel_by_stage:
            _dict['funnelByStage'] = self.funnel_by_stage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DashboardStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contractCount": obj.get("contractCount"),
            "receiptCount": obj.get("receiptCount"),
            "sampleCount": obj.get("sampleCount"),
            "reportCountByStatus": DashboardStatsReportCountByStatus.from_dict(obj.get("reportCountByStatus")) if obj.get("reportCountByStatus") is not None else None,
            "pendingTaskCount": obj.get("pendingTaskCount"),
            "todayTestCount": obj.get("todayTestCount"),
            "qualifiedRateByMaterial": DashboardStatsQualifiedRateByMaterial.from_dict(obj.get("qualifiedRateByMaterial")) if obj.get("qualifiedRateByMaterial") is not None else None,
            "reportOutputByStatus": DashboardStatsReportOutputByStatus.from_dict(obj.get("reportOutputByStatus")) if obj.get("reportOutputByStatus") is not None else None,
            "funnelByStage": DashboardStatsFunnelByStage.from_dict(obj.get("funnelByStage")) if obj.get("funnelByStage") is not None else None
        })
        return _obj


