# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from lab_management_system_fastapi.models.auth_context import AuthContext
from lab_management_system_fastapi.models.backend_registry import BackendRegistry
from lab_management_system_fastapi.models.token_storage_keys import TokenStorageKeys
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FrontendBindMetaFrontendBindSnapshot(BaseModel):
    """
    FrontendBindMetaFrontendBindSnapshot
    """ # noqa: E501
    registry: BackendRegistry = Field(description="已废弃 (ADR-0014);保留以维持 BackendRegistry schema 在 openapi.yaml 里的可达性")
    auth_context: AuthContext = Field(alias="authContext")
    token_keys: TokenStorageKeys = Field(alias="tokenKeys")
    __properties: ClassVar[List[str]] = ["registry", "authContext", "tokenKeys"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FrontendBindMetaFrontendBindSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of registry
        if self.registry:
            _dict['registry'] = self.registry.to_dict()
        # override the default output from pydantic by calling `to_dict()` of auth_context
        if self.auth_context:
            _dict['authContext'] = self.auth_context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of token_keys
        if self.token_keys:
            _dict['tokenKeys'] = self.token_keys.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FrontendBindMetaFrontendBindSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "registry": BackendRegistry.from_dict(obj.get("registry")) if obj.get("registry") is not None else None,
            "authContext": AuthContext.from_dict(obj.get("authContext")) if obj.get("authContext") is not None else None,
            "tokenKeys": TokenStorageKeys.from_dict(obj.get("tokenKeys")) if obj.get("tokenKeys") is not None else None
        })
        return _obj


