# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InspectionObject(BaseModel):
    """
    InspectionObject
    """ # noqa: E501
    code: StrictStr
    inspection_specialty_code: StrictStr = Field(alias="inspectionSpecialtyCode")
    source_project_no: StrictStr = Field(alias="sourceProjectNo")
    source_project_name: StrictStr = Field(alias="sourceProjectName")
    name: StrictStr
    is_optional_for_qualification: StrictBool = Field(alias="isOptionalForQualification")
    is_official: StrictBool = Field(alias="isOfficial")
    enabled: StrictBool
    sort_order: StrictInt = Field(alias="sortOrder")
    created_at: StrictStr = Field(alias="createdAt")
    updated_at: StrictStr = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["code", "inspectionSpecialtyCode", "sourceProjectNo", "sourceProjectName", "name", "isOptionalForQualification", "isOfficial", "enabled", "sortOrder", "createdAt", "updatedAt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InspectionObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InspectionObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "inspectionSpecialtyCode": obj.get("inspectionSpecialtyCode"),
            "sourceProjectNo": obj.get("sourceProjectNo"),
            "sourceProjectName": obj.get("sourceProjectName"),
            "name": obj.get("name"),
            "isOptionalForQualification": obj.get("isOptionalForQualification"),
            "isOfficial": obj.get("isOfficial"),
            "enabled": obj.get("enabled"),
            "sortOrder": obj.get("sortOrder"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


