# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lab_management_system_fastapi.models.inspection_parameter_source_type import InspectionParameterSourceType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InspectionParameter(BaseModel):
    """
    InspectionParameter
    """ # noqa: E501
    code: StrictStr
    name: StrictStr
    raw_name: StrictStr = Field(alias="rawName")
    canonical_name: StrictStr = Field(alias="canonicalName")
    method_text: Optional[StrictStr] = Field(default=None, alias="methodText")
    aliases: List[StrictStr]
    unit: Optional[StrictStr] = None
    source_type: InspectionParameterSourceType = Field(alias="sourceType")
    sort_order: StrictInt = Field(alias="sortOrder")
    created_at: StrictStr = Field(alias="createdAt")
    updated_at: StrictStr = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["code", "name", "rawName", "canonicalName", "methodText", "aliases", "unit", "sourceType", "sortOrder", "createdAt", "updatedAt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InspectionParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InspectionParameter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "name": obj.get("name"),
            "rawName": obj.get("rawName"),
            "canonicalName": obj.get("canonicalName"),
            "methodText": obj.get("methodText"),
            "aliases": obj.get("aliases"),
            "unit": obj.get("unit"),
            "sourceType": obj.get("sourceType"),
            "sortOrder": obj.get("sortOrder"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


