# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lab_management_system_fastapi.models.ext_field_def import ExtFieldDef
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InspectionReportName(BaseModel):
    """
    InspectionReportName
    """ # noqa: E501
    code: StrictStr
    name: StrictStr
    full_name: Optional[StrictStr] = Field(default=None, alias="fullName")
    template_path: Optional[StrictStr] = Field(default=None, alias="templatePath")
    summary_name: Optional[StrictStr] = Field(default=None, alias="summaryName")
    ext_fields: Optional[List[ExtFieldDef]] = Field(default=None, alias="extFields")
    description: Optional[StrictStr] = None
    sort_order: StrictInt = Field(alias="sortOrder")
    created_at: StrictStr = Field(alias="createdAt")
    updated_at: StrictStr = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["code", "name", "fullName", "templatePath", "summaryName", "extFields", "description", "sortOrder", "createdAt", "updatedAt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InspectionReportName from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ext_fields (list)
        _items = []
        if self.ext_fields:
            for _item in self.ext_fields:
                if _item:
                    _items.append(_item.to_dict())
            _dict['extFields'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InspectionReportName from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "name": obj.get("name"),
            "fullName": obj.get("fullName"),
            "templatePath": obj.get("templatePath"),
            "summaryName": obj.get("summaryName"),
            "extFields": [ExtFieldDef.from_dict(_item) for _item in obj.get("extFields")] if obj.get("extFields") is not None else None,
            "description": obj.get("description"),
            "sortOrder": obj.get("sortOrder"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


