# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lab_management_system_fastapi.models.qualification_level import QualificationLevel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ObjectParameterLink(BaseModel):
    """
    ObjectParameterLink
    """ # noqa: E501
    inspection_object_code: StrictStr = Field(alias="inspectionObjectCode")
    inspection_parameter_code: StrictStr = Field(alias="inspectionParameterCode")
    qualification_level: QualificationLevel = Field(alias="qualificationLevel")
    source_page: Optional[StrictInt] = Field(default=None, alias="sourcePage")
    remark: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["inspectionObjectCode", "inspectionParameterCode", "qualificationLevel", "sourcePage", "remark"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ObjectParameterLink from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ObjectParameterLink from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "inspectionObjectCode": obj.get("inspectionObjectCode"),
            "inspectionParameterCode": obj.get("inspectionParameterCode"),
            "qualificationLevel": obj.get("qualificationLevel"),
            "sourcePage": obj.get("sourcePage"),
            "remark": obj.get("remark")
        })
        return _obj


