# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Sample(BaseModel):
    """
    Sample
    """ # noqa: E501
    id: StrictStr
    tenant_id: StrictStr = Field(alias="tenantId")
    receipt_id: StrictStr = Field(alias="receiptId")
    sample_code: StrictStr = Field(alias="sampleCode")
    sample_name: Optional[StrictStr] = Field(default=None, alias="sampleName")
    model: Optional[StrictStr] = None
    specification: Optional[StrictStr] = None
    grade: Optional[StrictStr] = None
    brand: Optional[StrictStr] = None
    manufacturer: Optional[StrictStr] = None
    structural_part: Optional[StrictStr] = Field(default=None, alias="structuralPart")
    represent_quantity: Optional[StrictStr] = Field(default=None, alias="representQuantity")
    sample_quantity: Optional[StrictStr] = Field(default=None, alias="sampleQuantity")
    batch_number: Optional[StrictStr] = Field(default=None, alias="batchNumber")
    supply_unit: Optional[StrictStr] = Field(default=None, alias="supplyUnit")
    arrival_date: Optional[StrictStr] = Field(default=None, alias="arrivalDate")
    sampling_date: Optional[StrictStr] = Field(default=None, alias="samplingDate")
    curing_condition: Optional[StrictStr] = Field(default=None, alias="curingCondition")
    age: Optional[StrictStr] = None
    ext: Dict[str, StrictStr]
    remark: Optional[StrictStr] = None
    created_at: StrictStr = Field(alias="createdAt")
    updated_at: StrictStr = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "tenantId", "receiptId", "sampleCode", "sampleName", "model", "specification", "grade", "brand", "manufacturer", "structuralPart", "representQuantity", "sampleQuantity", "batchNumber", "supplyUnit", "arrivalDate", "samplingDate", "curingCondition", "age", "ext", "remark", "createdAt", "updatedAt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Sample from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Sample from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "tenantId": obj.get("tenantId"),
            "receiptId": obj.get("receiptId"),
            "sampleCode": obj.get("sampleCode"),
            "sampleName": obj.get("sampleName"),
            "model": obj.get("model"),
            "specification": obj.get("specification"),
            "grade": obj.get("grade"),
            "brand": obj.get("brand"),
            "manufacturer": obj.get("manufacturer"),
            "structuralPart": obj.get("structuralPart"),
            "representQuantity": obj.get("representQuantity"),
            "sampleQuantity": obj.get("sampleQuantity"),
            "batchNumber": obj.get("batchNumber"),
            "supplyUnit": obj.get("supplyUnit"),
            "arrivalDate": obj.get("arrivalDate"),
            "samplingDate": obj.get("samplingDate"),
            "curingCondition": obj.get("curingCondition"),
            "age": obj.get("age"),
            "ext": obj.get("ext"),
            "remark": obj.get("remark"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


