# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TokenStorageKeys(BaseModel):
    """
    前端持久化 key 命名约定;后端契约不感知,但前端实现必须遵守
    """ # noqa: E501
    access_token: StrictStr = Field(description="Bearer token", alias="accessToken")
    refresh_token: StrictStr = Field(description="refresh token(与 accessToken 分存,便于隔离 XSS 影响面)", alias="refreshToken")
    active_tenant_id: StrictStr = Field(description="当前选中租户 ID(authenticated 态缓存)", alias="activeTenantId")
    permissions_cache: StrictStr = Field(description="permissions 缓存(避免每次路由跳转都打 /auth/permissions)", alias="permissionsCache")
    __properties: ClassVar[List[str]] = ["accessToken", "refreshToken", "activeTenantId", "permissionsCache"]

    @field_validator('access_token')
    def access_token_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('lab.accessToken',):
            raise ValueError("must be one of enum values ('lab.accessToken')")
        return value

    @field_validator('refresh_token')
    def refresh_token_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('lab.refreshToken',):
            raise ValueError("must be one of enum values ('lab.refreshToken')")
        return value

    @field_validator('active_tenant_id')
    def active_tenant_id_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('lab.activeTenantId',):
            raise ValueError("must be one of enum values ('lab.activeTenantId')")
        return value

    @field_validator('permissions_cache')
    def permissions_cache_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('lab.permissions',):
            raise ValueError("must be one of enum values ('lab.permissions')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TokenStorageKeys from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TokenStorageKeys from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessToken": obj.get("accessToken"),
            "refreshToken": obj.get("refreshToken"),
            "activeTenantId": obj.get("activeTenantId"),
            "permissionsCache": obj.get("permissionsCache")
        })
        return _obj


