# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lab_management_system_fastapi.models.requirement_comparison import RequirementComparison
from lab_management_system_fastapi.models.requirement_judgment_mode import RequirementJudgmentMode
from lab_management_system_fastapi.models.requirement_value_type import RequirementValueType
from lab_management_system_fastapi.models.requirement_verification_status import RequirementVerificationStatus
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpdateTechnicalRequirementRequest(BaseModel):
    """
    UpdateTechnicalRequirementRequest
    """ # noqa: E501
    conditions: Optional[StrictStr] = None
    value_type: Optional[RequirementValueType] = Field(default=None, alias="valueType")
    min_value: Optional[StrictInt] = Field(default=None, alias="minValue")
    max_value: Optional[StrictInt] = Field(default=None, alias="maxValue")
    target_value: Optional[StrictStr] = Field(default=None, alias="targetValue")
    expression: Optional[StrictStr] = None
    unit: Optional[StrictStr] = None
    comparison: Optional[RequirementComparison] = None
    judgment_mode: Optional[RequirementJudgmentMode] = Field(default=None, alias="judgmentMode")
    verification_status: Optional[RequirementVerificationStatus] = Field(default=None, alias="verificationStatus")
    clause: Optional[StrictStr] = None
    source_page: Optional[StrictInt] = Field(default=None, alias="sourcePage")
    source_hash: Optional[StrictStr] = Field(default=None, alias="sourceHash")
    brand: Optional[StrictStr] = None
    model: Optional[StrictStr] = None
    grade: Optional[StrictStr] = None
    spec: Optional[StrictStr] = None
    sieve: Optional[StrictStr] = None
    remark: Optional[StrictStr] = None
    sort_order: Optional[StrictInt] = Field(default=None, alias="sortOrder")
    __properties: ClassVar[List[str]] = ["conditions", "valueType", "minValue", "maxValue", "targetValue", "expression", "unit", "comparison", "judgmentMode", "verificationStatus", "clause", "sourcePage", "sourceHash", "brand", "model", "grade", "spec", "sieve", "remark", "sortOrder"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpdateTechnicalRequirementRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpdateTechnicalRequirementRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conditions": obj.get("conditions"),
            "valueType": obj.get("valueType"),
            "minValue": obj.get("minValue"),
            "maxValue": obj.get("maxValue"),
            "targetValue": obj.get("targetValue"),
            "expression": obj.get("expression"),
            "unit": obj.get("unit"),
            "comparison": obj.get("comparison"),
            "judgmentMode": obj.get("judgmentMode"),
            "verificationStatus": obj.get("verificationStatus"),
            "clause": obj.get("clause"),
            "sourcePage": obj.get("sourcePage"),
            "sourceHash": obj.get("sourceHash"),
            "brand": obj.get("brand"),
            "model": obj.get("model"),
            "grade": obj.get("grade"),
            "spec": obj.get("spec"),
            "sieve": obj.get("sieve"),
            "remark": obj.get("remark"),
            "sortOrder": obj.get("sortOrder")
        })
        return _obj


