# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpdateSampleReceiptRequest(BaseModel):
    """
    UpdateSampleReceiptRequest
    """ # noqa: E501
    contract_id: Optional[StrictStr] = Field(default=None, alias="contractId")
    commission_code: Optional[StrictStr] = Field(default=None, alias="commissionCode")
    commission_date: Optional[StrictStr] = Field(default=None, alias="commissionDate")
    commission_register_code: Optional[StrictStr] = Field(default=None, alias="commissionRegisterCode")
    commission_register_date: Optional[StrictStr] = Field(default=None, alias="commissionRegisterDate")
    category_code: Optional[StrictStr] = Field(default=None, alias="categoryCode")
    project_name: Optional[StrictStr] = Field(default=None, alias="projectName")
    client_unit: Optional[StrictStr] = Field(default=None, alias="clientUnit")
    building_unit: Optional[StrictStr] = Field(default=None, alias="buildingUnit")
    supervisor_unit: Optional[StrictStr] = Field(default=None, alias="supervisorUnit")
    construction_unit: Optional[StrictStr] = Field(default=None, alias="constructionUnit")
    witness_unit: Optional[StrictStr] = Field(default=None, alias="witnessUnit")
    sampling_location: Optional[StrictStr] = Field(default=None, alias="samplingLocation")
    witness: Optional[StrictStr] = None
    witness_phone: Optional[StrictStr] = Field(default=None, alias="witnessPhone")
    inspector: Optional[StrictStr] = None
    inspector_phone: Optional[StrictStr] = Field(default=None, alias="inspectorPhone")
    received_by: Optional[StrictStr] = Field(default=None, alias="receivedBy")
    sample_source: Optional[StrictStr] = Field(default=None, alias="sampleSource")
    test_category: Optional[StrictStr] = Field(default=None, alias="testCategory")
    test_environment: Optional[StrictStr] = Field(default=None, alias="testEnvironment")
    main_equipment: Optional[StrictStr] = Field(default=None, alias="mainEquipment")
    test_operator: Optional[StrictStr] = Field(default=None, alias="testOperator")
    test_start_date: Optional[StrictStr] = Field(default=None, alias="testStartDate")
    test_end_date: Optional[StrictStr] = Field(default=None, alias="testEndDate")
    original_record_no: Optional[StrictStr] = Field(default=None, alias="originalRecordNo")
    remark: Optional[StrictStr] = None
    judgment_basis: Optional[List[StrictStr]] = Field(default=None, alias="judgmentBasis")
    testing_basis: Optional[List[StrictStr]] = Field(default=None, alias="testingBasis")
    test_parameters: Optional[List[StrictStr]] = Field(default=None, alias="testParameters")
    __properties: ClassVar[List[str]] = ["contractId", "commissionCode", "commissionDate", "commissionRegisterCode", "commissionRegisterDate", "categoryCode", "projectName", "clientUnit", "buildingUnit", "supervisorUnit", "constructionUnit", "witnessUnit", "samplingLocation", "witness", "witnessPhone", "inspector", "inspectorPhone", "receivedBy", "sampleSource", "testCategory", "testEnvironment", "mainEquipment", "testOperator", "testStartDate", "testEndDate", "originalRecordNo", "remark", "judgmentBasis", "testingBasis", "testParameters"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpdateSampleReceiptRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpdateSampleReceiptRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contractId": obj.get("contractId"),
            "commissionCode": obj.get("commissionCode"),
            "commissionDate": obj.get("commissionDate"),
            "commissionRegisterCode": obj.get("commissionRegisterCode"),
            "commissionRegisterDate": obj.get("commissionRegisterDate"),
            "categoryCode": obj.get("categoryCode"),
            "projectName": obj.get("projectName"),
            "clientUnit": obj.get("clientUnit"),
            "buildingUnit": obj.get("buildingUnit"),
            "supervisorUnit": obj.get("supervisorUnit"),
            "constructionUnit": obj.get("constructionUnit"),
            "witnessUnit": obj.get("witnessUnit"),
            "samplingLocation": obj.get("samplingLocation"),
            "witness": obj.get("witness"),
            "witnessPhone": obj.get("witnessPhone"),
            "inspector": obj.get("inspector"),
            "inspectorPhone": obj.get("inspectorPhone"),
            "receivedBy": obj.get("receivedBy"),
            "sampleSource": obj.get("sampleSource"),
            "testCategory": obj.get("testCategory"),
            "testEnvironment": obj.get("testEnvironment"),
            "mainEquipment": obj.get("mainEquipment"),
            "testOperator": obj.get("testOperator"),
            "testStartDate": obj.get("testStartDate"),
            "testEndDate": obj.get("testEndDate"),
            "originalRecordNo": obj.get("originalRecordNo"),
            "remark": obj.get("remark"),
            "judgmentBasis": obj.get("judgmentBasis"),
            "testingBasis": obj.get("testingBasis"),
            "testParameters": obj.get("testParameters")
        })
        return _obj


